### ISSUE TITLE
Connector Backpack PCB

### ISSUE THREAD

**Issue by Chrismettal** [Matt-London/pwnagotchi-flipper#11]
Thank you for making this app!

I have created a PCB to easily connect a Pi to the Flipper including an PCF8523 RTC on board specifically to use with your app.

I am linking from the board to your repo to show a specific usecase of the board. If you want, I would be happy if you linked back to the board from your app in case your users are looking for a cleaner way to connect their Pis to their Flippers.

Obviously I am totally fine if you don't want to do that. Though I would still like to link to your app if that's OK for you!

https://github.com/Chrismettal/flipper-zero-backpacks#raspberry-pi-zero-w

**Comment by Matt-London** [comment]
@Chrismettal Hey sorry for the delay! This looks great, I will definitely make an edit and link to you in the README.md. When I have more time I will have to try out the backpack for myself, seems like a great idea. Thank you for sharing!
