### ISSUE TITLE
Does not support new API

### ISSUE THREAD

**Issue by Matt-London** [Matt-London/pwnagotchi-flipper#13]
- The most updated Flipper Zero API is not supported with this implementation
- I will work on that soon so I can publish it to the Flipper app store

**Comment by ipx403** [comment]
When can it be completed? Thank you, I am looking forward to it.~

**Comment by Matt-London** [comment]
> When can it be completed? Thank you, I am looking forward to it.~

@ipx403 Hopefully within the next few weeks. At the latest sometime in May. I just need enough free time to sit down with it for a few hours.

**Comment by Matt-London** [comment]
I made a branch for this and will try to get things going soon. It seems like the API has changed a good bit so it may take some time for me to complete.

I will post any big updates on this enhancement here, otherwise you can follow along on the branch. After this work is complete I will move to get Flipagotchi on the Flipper app store.

**Comment by Matt-London** [comment]
I have updated the program and will submit the manifest file for the app store now.
