### ISSUE TITLE
Pi Zero 2 W fork compatibility

### ISSUE THREAD

**Issue by Chrismettal** [Matt-London/pwnagotchi-flipper#15]
Hey,

have you tested for compatibility with the [popular pwnagotchi fork](https://github.com/aluminum-ice/pwnagotchi) compatible with the Pi Zero 2 W?

I do not yet have a Zero 2, currently inbound to me, but the original pwnagotchi release was only compatible to first gen Pi Ws which are getting harder to come by.

**Comment by Matt-London** [comment]
@Chrismettal That depends on if they changed the API for plugins on the pwnagotchi side. If not then it should work fine, otherwise things will probably go wrong. I encourage you to try it out and please let me know how it turns out. Good luck!

**Comment by Chrismettal** [comment]
Can confirm, works fine on [Version 1.8.5](https://github.com/aluminum-ice/pwnagotchi/releases/tag/1.8.5) of the Pwnagotchi fork.

I had to install the plugin inside the users's home folder `/home/pi/pwnplug/PwnZero.py` and point the plugin directory to `/home/pi/pwnplug`, install PySerial manually as shown in the doc, add `dtoverlay=pi3-disable-bt`, `dtoverlay=disable-bt` to `/boot/config.txt` and remove `console=serial0,115200` from `/boot/cmdline.txt` afterwards, it connected just fine.

Test was done on Unleasehed 071e so not fully up to date on the flipper side.

**Comment by Chrismettal** [comment]
It doesn't update the name of the pwnagotchi and does not show all faces possible. Some strings are cut off. Though I am not 100% sure how much of that was present with the old versions of pwnagotchi.

**Comment by Matt-London** [comment]
@Chrismettal Great, glad you got everything working. As I work on the API update for the latest version of the Flipper API I will add any of the setup steps missing to the documentation.
