### ISSUE TITLE
Setup Errors

### ISSUE THREAD

**Issue by gabrielconlon** [Matt-London/pwnagotchi-flipper#7]
Can you add a quick walkthrough of setup?

I've got the Python script on a pwnagotchi and can run it, but get an error that it can't find file /dev/serial0

I've tried different combinations of UART=1 and console=serial0 or console=serial1 in config.txt and cmdline.txt

before I go to far down the rabbit hole just wanted to get your input.  I'd love to help contribute after getting up and running

**Comment by Matt-London** [comment]
I had to do some modification with the Pi's UART. If I remember correctly disabling Bluetooth in /boot/config.txt was the only step.

I've been pretty busy lately, but I will try and find time to write the setup instructions sometime this week. Agreed, that would help the momentum of the project. I'll keep this open and close it once I have those instructions pushed.

**Comment by Matt-London** [comment]
Setup steps have now been added to the README.md. Thank you for your critiques, I will now close this issue.
