### ISSUE TITLE
pyserial not installed in base Pwnagotchi install

### ISSUE THREAD

**Issue by Chrismettal** [Matt-London/pwnagotchi-flipper#9]
With a fresh Pwnagotchi install, the plugin won't load, since pyserial isn't installed by default.
You would see the following error in the pwnagotchi.log:

`[WARNING] error while loading /home/pi/pwnplug/PwnZero.py: No module named 'serial'`

When following the guide (only interfacing with the SD card without connecting to the pi) this is solved by downloading piserial from pip with `pip download pyserial` on your host machine, unzipping the resulting folder, and moving the `serial` folder over to `usr/lib/python3.7/` on the pi.

Maybe something like that can be addeed to the readme.

---

Thanks for this plugin btw! I'm about to create an adapter board specifically for this plugin, to have a pi zero mounted to the back of the Flipper cleanly.

**Comment by Matt-London** [comment]
Hmm, I have not run into that before. I can try and find time to do some testing this week and see if I can reproduce your issue. Thank you for letting me know

**Comment by Matt-London** [comment]
Just finished doing some testing and you are correct. I must have installed `pyserial` along the way and not documented it. I also caught an error in the `dtoverlay` statement. Thank you for bringing this to my attention, I will get a fix out shortly!
